/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PattimuraRouteImport } from './routes/pattimura'
import { Route as MarthaRouteImport } from './routes/martha'
import { Route as KuisRouteImport } from './routes/kuis'
import { Route as IndexRouteImport } from './routes/index'

const PattimuraRoute = PattimuraRouteImport.update({
  id: '/pattimura',
  path: '/pattimura',
  getParentRoute: () => rootRouteImport,
} as any)
const MarthaRoute = MarthaRouteImport.update({
  id: '/martha',
  path: '/martha',
  getParentRoute: () => rootRouteImport,
} as any)
const KuisRoute = KuisRouteImport.update({
  id: '/kuis',
  path: '/kuis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kuis': typeof KuisRoute
  '/martha': typeof MarthaRoute
  '/pattimura': typeof PattimuraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kuis': typeof KuisRoute
  '/martha': typeof MarthaRoute
  '/pattimura': typeof PattimuraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kuis': typeof KuisRoute
  '/martha': typeof MarthaRoute
  '/pattimura': typeof PattimuraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kuis' | '/martha' | '/pattimura'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kuis' | '/martha' | '/pattimura'
  id: '__root__' | '/' | '/kuis' | '/martha' | '/pattimura'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KuisRoute: typeof KuisRoute
  MarthaRoute: typeof MarthaRoute
  PattimuraRoute: typeof PattimuraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pattimura': {
      id: '/pattimura'
      path: '/pattimura'
      fullPath: '/pattimura'
      preLoaderRoute: typeof PattimuraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/martha': {
      id: '/martha'
      path: '/martha'
      fullPath: '/martha'
      preLoaderRoute: typeof MarthaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuis': {
      id: '/kuis'
      path: '/kuis'
      fullPath: '/kuis'
      preLoaderRoute: typeof KuisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KuisRoute: KuisRoute,
  MarthaRoute: MarthaRoute,
  PattimuraRoute: PattimuraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
